In [6]:
import numpy
fruit = ['organge','apple','pear','banana','kimi','apple','banana']
fruit.count('apple')


2

In [7]:
fruit.count('trangerrine')

0

In [8]:
fruit.index('banana')

3

In [9]:
fruit.index('banana',4)

6

In [10]:
fruit.reverse()


In [12]:
fruit

['banana', 'apple', 'kimi', 'banana', 'pear', 'apple', 'organge']

In [13]:
fruit.append('trangerrine')

In [14]:
fruit

['banana',
 'apple',
 'kimi',
 'banana',
 'pear',
 'apple',
 'organge',
 'trangerrine']

In [15]:
fruit.sort() # sort 是对原来的列表进行排序，sorted是返回一个新的列表

In [16]:
fruit

['apple',
 'apple',
 'banana',
 'banana',
 'kimi',
 'organge',
 'pear',
 'trangerrine']

In [18]:
fruit.pop()

'pear'

In [26]:
fruit1 = fruit.copy
# copy 的是浅拷贝，只拷贝了第一层，如果是多层的话，只拷贝第一层，第二层还是指向原来的列表
# builtin function id() 可以查看对象的内存地址



In [27]:
matrix = numpy.array([[1,2,3],[4,5,6],[7,8,9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
[[row[i] for row in matrix] for i in range(3)]

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [31]:
transposed = []
for i in range(3):
    transposed.append([row[i] for row in matrix])

transposed

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [32]:
knights = {'gallahad':'the pure','robin':'the brave'}

for k,v in knights.items():
    print(k,v)

gallahad the pure
robin the brave


In [33]:
for i,v in enumerate(['tic','tac','toe']):
    print(i,v)

0 tic
1 tac
2 toe


In [34]:
questions = ['name','quest','favorite color']

answers = ['lancelot','the holy grail','blue']

for q,a in zip(questions,answers):
    print('What is your {0}? It is {1}.'.format(q,a))
    

What is your name? It is lancelot.
What is your quest? It is the holy grail.
What is your favorite color? It is blue.


Python中提供了list容器，可以当作数组使用。但列表中的元素可以是任何对象，因此列表中保存的是对象的指针，这样一来，为了保存一个简单的列表[1,2,3]。就需要三个指针和三个整数对象。对于数值运算来说，这种结构显然不够高效。
Python虽然也提供了array模块，但其只支持一维数组，不支持多维数组，也没有各种运算函数。因而不适合数值运算。
NumPy的出现弥补了这些不足。

In [36]:
import numpy as np
# 常规创建方法
a = np.array([1,2,3])
b = np.array([2.0,3.0,4.0])
c = np.array([[1.0,2.0],[3.0,4.0]])
d = np.array([[1,2],[3,4]])

print(a) 
print(a.dtype)
print(b)
print(b.dtype)
print(c)
print(c.dtype)
print(d)
print(d.dtype)

[1 2 3]
int32
[2. 3. 4.]
float64
[[1. 2.]
 [3. 4.]]
float64
[[1 2]
 [3 4]]
int32


In [40]:

a = np.floor(10*np.random.random((3,4)))
a
a.shape

(3, 4)